theme: jekyll-theme-slate

title: Jeff Suliga
description: In Development
version: Version 13.1.8

# DO NOT change baseurl
baseurl: ""
url: "https://jeff-suliga.github.io"
imgurl: "https://jeff-suliga.github.io/images"
imgposturl: "https://jeff-suliga.github.io/images/Posts"
posturl: "https://jeff-suliga.github.io/Posts"

email: suligajw@vt.edu
github_username: jeff-suliga
insta_username: jeff.suliga