theme: jekyll-theme-slate

title: Jeff Suliga's title
description: Test Description
version: Version 5.3.5

name: JS

baseurl: ""
imgurl: "{{ site.baseurl }}/images"

email: suligajw@vt.edu
github_username: jeff-suliga
insta_username: jeff.suliga

google_analytics: Jeff Suliga
