theme: jekyll-theme-slate

title: Jeff Suliga's title
description: Finally converting to HTML
version: Version 7.1.8

name: JS

baseurl: ""
url: "http://jeff-suliga.github.io"
imgurl: "https://jeff-suliga.github.io/images"
posturl: "https://jeff-suliga.github.io/Posts"

email: suligajw@vt.edu
github_username: jeff-suliga
insta_username: jeff.suliga

google_analytics: G-87C1PXZFS2