theme: jekyll-theme-slate

title: Jeff Suliga's title
description: Version 5.2.2
name: JS

email: suligajw@vt.edu
github_username: jeff-suliga
insta_username: jeff.suliga

google_analytics: Jeff Suliga
