theme: jekyll-theme-slate

title: Jeff Suliga's title
description: Finally converting to HTML
version: Version 6.1.6

name: JS

baseurl: ""
url: "http://jeff-suliga.github.io"
imgurl: "https://jeff-suliga.github.io/images"

email: suligajw@vt.edu
github_username: jeff-suliga
insta_username: jeff.suliga

google_analytics: Jeff Suliga
