theme: jekyll-theme-slate

title: Jeff Suliga's title
description: Test Description
version: Version 5.3.1

name: JS

baseurl: ""

email: suligajw@vt.edu
github_username: jeff-suliga
insta_username: jeff.suliga

google_analytics: Jeff Suliga
