theme: jekyll-theme-slate

title: Jeff Suliga's title
description: Finally converted to HTML
version: Version 8.11.3

name: Jeff Suliga

baseurl: ""
url: "http://jeff-suliga.github.io"
imgurl: "https://jeff-suliga.github.io/images"
imgposturl: "https://jeff-suliga.github.io/images/Posts"
posturl: "https://jeff-suliga.github.io/Posts"

email: suligajw@vt.edu
github_username: jeff-suliga
insta_username: jeff.suliga