theme: jekyll-theme-slate

title: Jeff Suliga
# description: Hello World
version: Version 10.3.5

# DO NOT change baseurl
baseurl: ""
url: "https://jeff-suliga.github.io"
imgurl: "https://jeff-suliga.github.io/images"
imgposturl: "https://jeff-suliga.github.io/images/Posts"
posturl: "https://jeff-suliga.github.io/Posts"

email: suligajw@vt.edu
github_username: jeff-suliga
insta_username: jeff.suliga